# Neural Networks and Deep Learning Spring 1400 <img src = 'https://ece.ut.ac.ir/cict-theme/images/footer-logo.png' alt="Tehran-University-Logo" width="150" height="150" align="right">
## Homework 3 - Question 1


### By Omid Vaheb
### 810196582

## Importing required libraries

In [78]:
import numpy as np
import random
import copy

## Generating Dataset

In [79]:
A = [-1, -1, -1, 1, -1, -1, -1,
     -1, -1, -1, 1, -1, -1, -1,
     -1, -1, -1, 1, -1, -1, -1,
     -1, -1, 1, -1, 1, -1, -1,
     -1, -1, 1, -1, 1, -1, -1,
     -1, 1, 1, 1, 1, 1, -1,
     -1, 1, -1, -1, -1, 1, -1,
     -1, 1, -1, -1, -1, 1, -1,
     1, 1, 1, -1, 1, 1, 1]
AA = [-1, 1, -1,
      1, -1, 1,
      1, 1, 1,
      1, -1, 1,
      1, -1, 1]
B = [1, 1, 1, 1, 1, 1, 1,
     1, -1, -1, -1, -1, -1, 1,
     1, -1, -1, -1, -1, 1, -1,
     1, -1, -1, -1, 1, -1, -1,
     1, 1, 1, 1, -1, -1, -1,
     1, -1, -1, -1, 1, -1, -1,
     1, -1, -1, -1, -1, 1, -1,
     1, -1, -1, -1, -1, -1, 1,
     1, 1, 1, 1, 1, 1, 1]
BB = [1, 1, -1,
      1, -1, 1,
      1, 1, -1,
      1, -1, 1,
      1, 1, -1]
C = [-1, -1, 1, 1, 1, 1, -1,
     -1, 1, -1, -1, -1, -1, 1,
     1, -1, -1, -1, -1, -1, -1,
     1, -1, -1, -1, -1, -1, -1,
     1, -1, -1, -1, -1, -1, -1,
     1, -1, -1, -1, -1, -1, -1,
     1, -1, -1, -1, -1, -1, -1,
     -1, 1, -1, -1, -1, -1, 1,
     -1, -1, 1, 1, 1, 1, -1]
CC = [-1, 1, 1,
      1, -1, -1,
      1, -1, -1,
      1, -1, -1,
      -1, 1, 1]

In [80]:
letters = [np.array(A), np.array(B), np.array(C)]
outputs = [np.array(AA), np.array(BB), np.array(CC)]

## Initializing weight matrix

In [81]:
W = [[0] * 15] * 63
W = np.array(W)

##Training Model

In [82]:
for index in range(3):
  s = letters[index]
  t = outputs[index]
  for i in range(63):
    for j in range(15):
      W[i][j] += s[i] * t[j]

## Evaluating Model

In [83]:
for index in range(3):
  s = letters[index]
  t = outputs[index]
  out = []
  for j in range(15):
    temp = 0
    for i in range(63):
      temp += s[i] * W[i][j]
    if temp >= 0:
      out.append(1)
    else:
      out.append(-1)
  print("Original Output:")
  print(t)
  print("Model Output:")
  print(np.array(out))
  error = 0
  for i in range(15):
    error += abs(t[i] - out[i])
  print("Error =", int(error / 2))

Original Output:
[-1  1 -1  1 -1  1  1  1  1  1 -1  1  1 -1  1]
Model Output:
[-1  1 -1  1 -1  1  1  1  1  1 -1  1  1 -1  1]
Error = 0
Original Output:
[ 1  1 -1  1 -1  1  1  1 -1  1 -1  1  1  1 -1]
Model Output:
[ 1  1 -1  1 -1  1  1  1 -1  1 -1  1  1  1 -1]
Error = 0
Original Output:
[-1  1  1  1 -1 -1  1 -1 -1  1 -1 -1 -1  1  1]
Model Output:
[-1  1  1  1 -1 -1  1 -1 -1  1 -1 -1 -1  1  1]
Error = 0


#Evaluation by test data with 10% noise

In [89]:
for index in range(3):
  s = copy.deepcopy(letters[index])
  t = outputs[index]
  for i in range(63):
    if random.random() <= 0.1:
      s[i] = s[i] * -1
  out = []
  for j in range(15):
    temp = 0
    for i in range(63):
      temp += s[i] * W[i][j]
    if temp >= 0:
      out.append(1)
    else:
      out.append(-1)
  print("Original Input:")
  print(letters[index])
  print("Noisy Input:")
  print(s)
  changes = 0
  for i in range(63):
    changes += abs(letters[index][i] - s[i])
  print("Number of changes =", int(changes / 2))
  print("Original Output:")
  print(t)
  print("Model Output:")
  print(np.array(out))
  error = 0
  for i in range(15):
    error += abs(t[i] - out[i])
  print("Error =", int(error / 2))

Original Input:
[-1 -1 -1  1 -1 -1 -1 -1 -1 -1  1 -1 -1 -1 -1 -1 -1  1 -1 -1 -1 -1 -1  1
 -1  1 -1 -1 -1 -1  1 -1  1 -1 -1 -1  1  1  1  1  1 -1 -1  1 -1 -1 -1  1
 -1 -1  1 -1 -1 -1  1 -1  1  1  1 -1  1  1  1]
Noisy Input:
[-1 -1 -1  1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1  1  1 -1 -1 -1 -1  1
 -1  1 -1 -1 -1 -1  1 -1  1 -1 -1 -1  1  1 -1  1 -1 -1 -1  1  1  1 -1 -1
 -1 -1  1 -1 -1 -1  1 -1  1 -1  1  1  1  1  1]
Number of changes = 9
Original Output:
[-1  1 -1  1 -1  1  1  1  1  1 -1  1  1 -1  1]
Model Output:
[-1  1 -1  1 -1  1  1  1  1  1 -1  1  1 -1  1]
Error = 0
Original Input:
[ 1  1  1  1  1  1  1  1 -1 -1 -1 -1 -1  1  1 -1 -1 -1 -1  1 -1  1 -1 -1
 -1  1 -1 -1  1  1  1  1 -1 -1 -1  1 -1 -1 -1  1 -1 -1  1 -1 -1 -1 -1  1
 -1  1 -1 -1 -1 -1 -1  1  1  1  1  1  1  1  1]
Noisy Input:
[ 1  1 -1  1  1  1  1  1 -1 -1 -1 -1 -1  1  1 -1 -1  1  1  1 -1  1 -1 -1
 -1  1  1 -1  1  1  1  1 -1 -1 -1 -1 -1  1 -1  1 -1 -1  1 -1 -1 -1 -1  1
 -1  1 -1 -1 -1 -1 -1  1  1 -1  1 -1  1  1  1]
Number of cha

#Evaluation by test data with 25% noise

In [93]:
for index in range(3):
  s = copy.deepcopy(letters[index])
  t = outputs[index]
  for i in range(63):
    if random.random() <= 0.25:
      s[i] = s[i] * -1
  out = []
  for j in range(15):
    temp = 0
    for i in range(63):
      temp += s[i] * W[i][j]
    if temp >= 0:
      out.append(1)
    else:
      out.append(-1)
  print("Original Input:")
  print(letters[index])
  print("Noisy Input:")
  print(s)
  changes = 0
  for i in range(63):
    changes += abs(letters[index][i] - s[i])
  print("Number of changes =", int(changes / 2))
  print("Original Output:")
  print(t)
  print("Model Output:")
  print(np.array(out))
  error = 0
  for i in range(15):
    error += abs(t[i] - out[i])
  print("Error =", int(error / 2))

Original Input:
[-1 -1 -1  1 -1 -1 -1 -1 -1 -1  1 -1 -1 -1 -1 -1 -1  1 -1 -1 -1 -1 -1  1
 -1  1 -1 -1 -1 -1  1 -1  1 -1 -1 -1  1  1  1  1  1 -1 -1  1 -1 -1 -1  1
 -1 -1  1 -1 -1 -1  1 -1  1  1  1 -1  1  1  1]
Noisy Input:
[-1 -1 -1  1 -1 -1 -1  1 -1 -1 -1 -1 -1  1 -1 -1 -1  1 -1 -1  1 -1  1  1
 -1  1 -1 -1 -1 -1  1  1  1 -1 -1 -1  1  1  1 -1  1 -1 -1 -1 -1 -1 -1  1
 -1 -1  1 -1 -1 -1  1 -1 -1 -1  1 -1  1  1 -1]
Number of changes = 11
Original Output:
[-1  1 -1  1 -1  1  1  1  1  1 -1  1  1 -1  1]
Model Output:
[-1  1 -1  1 -1  1  1  1  1  1 -1  1  1 -1  1]
Error = 0
Original Input:
[ 1  1  1  1  1  1  1  1 -1 -1 -1 -1 -1  1  1 -1 -1 -1 -1  1 -1  1 -1 -1
 -1  1 -1 -1  1  1  1  1 -1 -1 -1  1 -1 -1 -1  1 -1 -1  1 -1 -1 -1 -1  1
 -1  1 -1 -1 -1 -1 -1  1  1  1  1  1  1  1  1]
Noisy Input:
[ 1  1  1  1  1  1  1  1  1 -1 -1 -1 -1  1  1 -1  1 -1 -1  1  1 -1 -1 -1
 -1  1 -1  1  1  1 -1  1 -1 -1 -1  1 -1 -1 -1  1 -1  1  1 -1 -1 -1 -1 -1
 -1 -1 -1 -1 -1  1 -1  1  1  1 -1  1  1  1 -1]
Number of ch

#Evaluation by test data with 10% disturbance

In [94]:
for index in range(3):
  s = copy.deepcopy(letters[index])
  t = outputs[index]
  for i in range(63):
    if random.random() <= 0.1:
      s[i] = 0
  out = []
  for j in range(15):
    temp = 0
    for i in range(63):
      temp += s[i] * W[i][j]
    if temp >= 0:
      out.append(1)
    else:
      out.append(-1)
  print("Original Input:")
  print(letters[index])
  print("Noisy Input:")
  print(s)
  changes = 0
  for i in range(63):
    changes += abs(letters[index][i] - s[i])
  print("Number of changes =", int(changes / 2))
  print("Original Output:")
  print(t)
  print("Model Output:")
  print(np.array(out))
  error = 0
  for i in range(15):
    error += abs(t[i] - out[i])
  print("Error =", int(error / 2))

Original Input:
[-1 -1 -1  1 -1 -1 -1 -1 -1 -1  1 -1 -1 -1 -1 -1 -1  1 -1 -1 -1 -1 -1  1
 -1  1 -1 -1 -1 -1  1 -1  1 -1 -1 -1  1  1  1  1  1 -1 -1  1 -1 -1 -1  1
 -1 -1  1 -1 -1 -1  1 -1  1  1  1 -1  1  1  1]
Noisy Input:
[-1 -1 -1  1 -1 -1 -1 -1 -1 -1  1 -1 -1 -1 -1 -1 -1  1 -1 -1 -1 -1 -1  1
 -1  1 -1 -1 -1 -1  1 -1  1 -1 -1 -1  1  0  1  1  1 -1 -1  1 -1 -1 -1  1
  0 -1  1 -1 -1  0  1 -1  1  1  1  0  0  1  1]
Number of changes = 2
Original Output:
[-1  1 -1  1 -1  1  1  1  1  1 -1  1  1 -1  1]
Model Output:
[-1  1 -1  1 -1  1  1  1  1  1 -1  1  1 -1  1]
Error = 0
Original Input:
[ 1  1  1  1  1  1  1  1 -1 -1 -1 -1 -1  1  1 -1 -1 -1 -1  1 -1  1 -1 -1
 -1  1 -1 -1  1  1  1  1 -1 -1 -1  1 -1 -1 -1  1 -1 -1  1 -1 -1 -1 -1  1
 -1  1 -1 -1 -1 -1 -1  1  1  1  1  1  1  1  1]
Noisy Input:
[ 1  1  0  1  1  1  1  1 -1 -1 -1 -1 -1  1  1 -1 -1 -1 -1  1 -1  1 -1 -1
 -1  1  0 -1  0  0  1  1 -1 -1 -1  1 -1 -1  0  1 -1 -1  1 -1 -1 -1 -1  1
  0  1 -1 -1 -1 -1 -1  1  1  1  1  1  1  1  1]
Number of cha

#Evaluation by test data with 25% disturbance

In [95]:
for index in range(3):
  s = copy.deepcopy(letters[index])
  t = outputs[index]
  for i in range(63):
    if random.random() <= 0.25:
      s[i] = 0
  out = []
  for j in range(15):
    temp = 0
    for i in range(63):
      temp += s[i] * W[i][j]
    if temp >= 0:
      out.append(1)
    else:
      out.append(-1)
  print("Original Input:")
  print(letters[index])
  print("Noisy Input:")
  print(s)
  changes = 0
  for i in range(63):
    changes += abs(letters[index][i] - s[i])
  print("Number of changes =", int(changes / 2))
  print("Original Output:")
  print(t)
  print("Model Output:")
  print(np.array(out))
  error = 0
  for i in range(15):
    error += abs(t[i] - out[i])
  print("Error =", int(error / 2))

Original Input:
[-1 -1 -1  1 -1 -1 -1 -1 -1 -1  1 -1 -1 -1 -1 -1 -1  1 -1 -1 -1 -1 -1  1
 -1  1 -1 -1 -1 -1  1 -1  1 -1 -1 -1  1  1  1  1  1 -1 -1  1 -1 -1 -1  1
 -1 -1  1 -1 -1 -1  1 -1  1  1  1 -1  1  1  1]
Noisy Input:
[ 0 -1 -1  1 -1  0 -1 -1  0 -1  0 -1 -1  0  0 -1 -1  1 -1 -1 -1 -1 -1  1
  0  1 -1 -1 -1 -1  1 -1  1  0 -1 -1  0  1  1  1  1  0 -1  1 -1 -1 -1  1
  0 -1  1 -1  0 -1  0 -1  1  1  1 -1  1  1  1]
Number of changes = 6
Original Output:
[-1  1 -1  1 -1  1  1  1  1  1 -1  1  1 -1  1]
Model Output:
[-1  1 -1  1 -1  1  1  1  1  1 -1  1  1 -1  1]
Error = 0
Original Input:
[ 1  1  1  1  1  1  1  1 -1 -1 -1 -1 -1  1  1 -1 -1 -1 -1  1 -1  1 -1 -1
 -1  1 -1 -1  1  1  1  1 -1 -1 -1  1 -1 -1 -1  1 -1 -1  1 -1 -1 -1 -1  1
 -1  1 -1 -1 -1 -1 -1  1  1  1  1  1  1  1  1]
Noisy Input:
[ 0  1  1  1  0  1  0  1  0 -1 -1 -1 -1  1  1 -1 -1  0  0  1 -1  1 -1 -1
 -1  0 -1 -1  0  1  1  1 -1 -1 -1  0 -1  0  0  1 -1 -1  1 -1  0 -1 -1  1
 -1  1  0 -1 -1 -1 -1  1  1  0  0  0  1  1  0]
Number of cha